[package]
name = "rocketmine"
version = "0.1.0"
authors = ["djdisodo <djdisodo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raknet-rs = { path = "raklib-rs" }
regex = "1.3"
log4rs = "0.13"